name: stady1 project
on:
  push:
    branches:
      - main
    pull_request:
      branches:
        - main

jobs:
  first:
    name: install ubuntu
    runs-on: ubuntu-latest
    services:
      db:
        image : postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: stady1db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Update
        run: sudo apt update
      - name: check out repo
        uses: actions/checkout@v3
      - name: Install python3-pip
        run: sudo apt install python3-pip
      - name: Requirements install
        run: pip install -r re.txt
      - name: Run test
        env:
          DJANGO_SETTINGS_MODULE : stady1.settings.local
          SECRET_KEY : django-insecure-ktrohk9cwg*2u*t3exj6y=d4aj9!@oq%sowvhwxuzjexc)0vpp
          SQL_ENGINE: django.db.backends.postgresql
          SQL_DATABASE: stady1db
          SQL_USER: postgres
          SQL_PASSWORD: 1
          SQL_HOST: localhost
          SQL_PORT: 5432

        run:
          python manage.py test
          python manage.py migrate

