name: stady1 project
on:
  push:
    branches:
      - master

jobs:
  first:
    name: install ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Update
        run: sudo apt update
      - name: check out repo
        uses: actions/checkout@v3
      - name: Install python3-pip
        run: sudo apt install python3-pip
      - name: Requirements install
        run: pip install -r re.txt
      - name: Run test
        env:
          DJANGO_SETTINGS_MODULE: stady1.settings.local
          SECRET_KEY: django-insecure-ktrohk9cwg*2u*t3exj6y=d4aj9!@oq%sowvhwxuzjexc)0vpp
        run: python manage.py test

